version: '3.4'
 
networks:
  generalapicontainer-dev:
    driver: bridge 
 
services:
  generalapicontainer:
    image: generalapicontainer:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"     
    environment:
      DB_CONNECTION_STRING: "host=ec2-52-23-45-36.compute-1.amazonaws.com;port=5432;database=d1n2lij7ekk727;username=lnwhcurhqehzvu;password=2b2743aa852e18c515859f8ae737a3a38bb313ff9e6bd3d977628c7656db104e;SSL Mode=Require;Trust Server Certificate=true"
    networks:
      - generalapicontainer-dev