version: '3.4'
 
networks:
  generalapicontainer-dev:
    driver: bridge 
 
services:
  generalapicontainer:
    image: generalapicontainer:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"     
    environment:
      DB_CONNECTION_STRING: "host=host.docker.internal;port=5432;database=generalviwit;username=postgres;password="
    networks:
      - generalapicontainer-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "generalviwit"
    networks:
      - generalapicontainer-dev
volumes:
  db_volume: